### ISSUE TITLE
No Background

### ISSUE THREAD

**Issue by TheXtreamYT01** [Naifen-Phoxidas/esx_identity#4]
Hi the Background image was not found... Please reupload it.
Proof: https://i.ibb.co/tb9NCqR/zLPdIOJ.jpg

**Comment by Naifen-Phoxidas** [comment]
Yeah. I will fix this later.

**Comment by kyledeluxe** [comment]
Hey, any update?

**Comment by kyledeluxe** [comment]
@Naifen-Phoxidas

**Comment by Naifen-Phoxidas** [comment]
I have add an new background
